info/accounts/urls.py
<<<<<<< HEAD
from django.urls import path, re_path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.view_logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
=======
from django.urls import path, re_path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.view_logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
]

info/asitis/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "asitis"

urlpatterns = [
    path('', views.base, name="base"),
    path('detail/<int:pk>', views.detail, name="detail"),
    # path('like', views.comment_like, name='comment_like'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/config/urls.py
<<<<<<< HEAD
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('asitis/', include('asitis.urls')),
    path('notice_spider/', include('notice_spider.urls')),
]

=======
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('asitis/', include('asitis.urls')),
    path('notice_spider/', include('notice_spider.urls')),
]

>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/accounts/models.py
<<<<<<< HEAD
from django.db import models
from django.conf import settings


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='사용자')
    email = models.CharField(blank=True, max_length=30, verbose_name='소식 받을 이메일')
    telegram_id = models.CharField(blank=True, max_length=30, verbose_name='소식 받을 텔레그램')
    my_tags = models.TextField(blank=True, verbose_name='내가 선택한 태그')
    my_jokbo = models.TextField(blank=True, verbose_name='내가 선택한 족보')
=======
from django.db import models
from django.conf import settings


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='사용자')
    email = models.CharField(blank=True, max_length=30, verbose_name='소식 받을 이메일')
    telegram_id = models.CharField(blank=True, max_length=30, verbose_name='소식 받을 텔레그램')
    my_tags = models.TextField(blank=True, verbose_name='내가 선택한 태그')
    my_jokbo = models.TextField(blank=True, verbose_name='내가 선택한 족보')
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa

info/accounts/forms.py
<<<<<<< HEAD
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


def validate_school_email(value):
    if "@uos.ac.kr" not in value:
        raise forms.ValidationError("서울시립대학교 이메일 형식만 아이디로 사용가능합니다.")
    else:
        return value


def unique_nickname(value):
    for user in User.objects.all():
        print(user.last_name)
        if value == user.last_name:
            raise forms.ValidationError("이미 존재하는 아이디 입니다.")
    return value


class SignupForm(UserCreationForm):
    username = forms.EmailField(required=True, validators=[validate_school_email])
    nickname = forms.CharField(max_length=8, required=True, validators=[unique_nickname])

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['username']
        user.last_name = self.cleaned_data['nickname']
        if commit:
            user.save()
=======
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


def validate_school_email(value):
    if "@uos.ac.kr" not in value:
        raise forms.ValidationError("서울시립대학교 이메일 형식만 아이디로 사용가능합니다.")
    else:
        return value


def unique_nickname(value):
    for user in User.objects.all():
        print(user.last_name)
        if value == user.last_name:
            raise forms.ValidationError("이미 존재하는 아이디 입니다.")
    return value


class SignupForm(UserCreationForm):
    username = forms.EmailField(required=True, validators=[validate_school_email])
    nickname = forms.CharField(max_length=8, required=True, validators=[unique_nickname])

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['username']
        user.last_name = self.cleaned_data['nickname']
        if commit:
            user.save()
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
        return user

info/accounts/views.py
<<<<<<< HEAD
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as logedin, logout, authenticate
from .forms import SignupForm
from django.http import HttpResponse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.contrib import messages

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage


def login(request):
    form = AuthenticationForm(data=request.POST)
    alert_message = ""
    if request.method == 'POST':
        if form.is_valid():
            user = form.get_user()
            logedin(request, user)
            # return redirect(request.path)
            return redirect('base_app:base')
        else:
            form = AuthenticationForm()
            alert_message = "아이디나 비밀번호를 바르게 입력해주세요."
    ctx = {
        'form': form,
        'alert_message': alert_message,
    }
    return render(request, 'accounts/login.html', ctx)


def view_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('base_app:base')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # form.alert = "회원가입에 성공하셨습니다. 더 많은 서비스 이용을 위해 로그인 해주세요."
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('accounts/user_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your blog account.'
            to_email = form.cleaned_data.get('username')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse(
                '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                'justify-content: center; align-items: center;">'
                '<a href="https://portal.uos.ac.kr/user/login.face">'
                '학교 이메일</a><span>로 인증 링크가 전송되었습니다.</span>'
                '</div>'
            )
        else:
            alert_message = "이미 존재하는 닉네임입니다."
            form = SignupForm()
            ctx = {
                'form': form,
                'alert_message': alert_message,
            }
            return render(request, 'accounts/signup.html', ctx)
    else:
        form = SignupForm()
        ctx = {'form': form}
        return render(request, 'accounts/signup.html', ctx)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        logedin(request, user)
        return redirect('base_app:base')
    else:
        return HttpResponse('비정상적인 접근입니다.')
=======
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as logedin, logout, authenticate
from .forms import SignupForm
from django.http import HttpResponse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.contrib import messages

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage


def login(request):
    form = AuthenticationForm(data=request.POST)
    alert_message = ""
    if request.method == 'POST':
        if form.is_valid():
            user = form.get_user()
            logedin(request, user)
            # return redirect(request.path)
            return redirect('base_app:base')
        else:
            form = AuthenticationForm()
            alert_message = "아이디나 비밀번호를 바르게 입력해주세요."
    ctx = {
        'form': form,
        'alert_message': alert_message,
    }
    return render(request, 'accounts/login.html', ctx)


def view_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('base_app:base')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # form.alert = "회원가입에 성공하셨습니다. 더 많은 서비스 이용을 위해 로그인 해주세요."
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('accounts/user_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your blog account.'
            to_email = form.cleaned_data.get('username')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse(
                '<div style="font-size: 40px; width: 100%; height:100%; display:flex; text-align:center; '
                'justify-content: center; align-items: center;">'
                '<a href="https://portal.uos.ac.kr/user/login.face">'
                '학교 이메일</a><span>로 인증 링크가 전송되었습니다.</span>'
                '</div>'
            )
        else:
            alert_message = "이미 존재하는 닉네임입니다."
            form = SignupForm()
            ctx = {
                'form': form,
                'alert_message': alert_message,
            }
            return render(request, 'accounts/signup.html', ctx)
    else:
        form = SignupForm()
        ctx = {'form': form}
        return render(request, 'accounts/signup.html', ctx)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        logedin(request, user)
        return redirect('base_app:base')
    else:
        return HttpResponse('비정상적인 접근입니다.')
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa

info/accounts/templates/accounts/login.html
<<<<<<< HEAD
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>bld | 서울시립대 음식점</title>
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
</head>
<body>

{% if not user.is_authenticated %}
<div class="center">
  {% block log %}
  <div class="login_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="id">
        <input class="login_required" type="text" name="username" placeholder="회원 ID"
               required />
      </div>
      <div class="password">
        <input class="login_required" type="password" name="password" placeholder="비밀번호"
               required/>
      </div>
      <button class="login_required login_btn" type="submit">로그인</button>
      <div class="settings">
        <div class="login_save">로그인 유지(예정)</div>
    {#    <span><a href="#">회원가입</a></span>#}
        <div class="signup"><a href="#">회원가입</a></div>
      </div>
    </form>
  </div>
  {% endblock %}
</div>
{% else %}
<div class="center">
  <div class="login_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
  </div>
</div>
{% endif %}

</body>

  <!--jquery-->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script>
{% if user.is_authenticated %}
    alert("비정상적인 접근입니다");
{% endif %}
{% if alert_message %}
    alert("{{ alert_message }}");
{% endif %}
</script>
=======
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>bld | 서울시립대 음식점</title>
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
</head>
<body>

{% if not user.is_authenticated %}
<div class="center">
  {% block log %}
  <div class="login_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="id">
        <input class="login_required" type="text" name="username" placeholder="회원 ID"
               required />
      </div>
      <div class="password">
        <input class="login_required" type="password" name="password" placeholder="비밀번호"
               required/>
      </div>
      <button class="login_required login_btn" type="submit">로그인</button>
      <div class="settings">
        <div class="login_save">로그인 유지(예정)</div>
    {#    <span><a href="#">회원가입</a></span>#}
        <div class="signup"><a href="#">회원가입</a></div>
      </div>
    </form>
  </div>
  {% endblock %}
</div>
{% else %}
<div class="center">
  <div class="login_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
  </div>
</div>
{% endif %}

</body>

  <!--jquery-->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script>
{% if user.is_authenticated %}
    alert("비정상적인 접근입니다");
{% endif %}
{% if alert_message %}
    alert("{{ alert_message }}");
{% endif %}
</script>
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
</html>

info/accounts/templates/accounts/signup.html
<<<<<<< HEAD
{% extends "accounts/login.html" %}

{% block log %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">

  <div class="signup_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
    <form action="" method="POST" autocomplete="off">
      {% csrf_token %}
  {#    {{ form.as_p }}#}
  {#    <button style="background: black; height: 10px" type="submit"></button>#}
      <div class="id">
        <input class="signup_required" type="text" name="username" placeholder="시립대 포털 ID@uos.ac.kr"
               required pattern="^[a-z0-9._%+-]+@uos.ac.kr$" oninvalid="this.setCustomValidity('서울시립대학교 이메일 형식만 아이디로 사용가능합니다.')"
               oninput="this.setCustomValidity('')" autocomplete="off"/>
      </div>
      <div class="password">
        <input class="signup_required" type="password" name="password1" placeholder="비밀번호"
               required autocomplete="off"/>
      </div>
      <div class="password">
        <input class="signup_required" type="password" name="password2" placeholder="비밀번호(확인)"
               required autocomplete="off"/>
      </div>
      <div class="nickname">
        <input class="signup_required" type="text" name="nickname" placeholder="닉네임(8자 이하)"
               required pattern="^[a-zA-Z0-9가-힣]{1,8}$" oninvalid="this.setCustomValidity('8자 이하만 가능합니다.')"
               oninput="this.setCustomValidity('')"  autocomplete="off"/>
      </div>
      <button class="signup_required signup_btn">회원가입</button>
    </form>
  </div>


  <!--jquery-->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script>
{% if alert_message %}
    alert(alert_message);
{% endif %}
</script>

=======
{% extends "accounts/login.html" %}

{% block log %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">

  <div class="signup_box">
    <div class="logo"><a href="#"><img src="{% static 'base_app/images/logo.png' %}" width="100"></a></div>
    <form action="" method="POST" autocomplete="off">
      {% csrf_token %}
  {#    {{ form.as_p }}#}
  {#    <button style="background: black; height: 10px" type="submit"></button>#}
      <div class="id">
        <input class="signup_required" type="text" name="username" placeholder="시립대 포털 ID@uos.ac.kr"
               required pattern="^[a-z0-9._%+-]+@uos.ac.kr$" oninvalid="this.setCustomValidity('서울시립대학교 이메일 형식만 아이디로 사용가능합니다.')"
               oninput="this.setCustomValidity('')" autocomplete="off"/>
      </div>
      <div class="password">
        <input class="signup_required" type="password" name="password1" placeholder="비밀번호"
               required autocomplete="off"/>
      </div>
      <div class="password">
        <input class="signup_required" type="password" name="password2" placeholder="비밀번호(확인)"
               required autocomplete="off"/>
      </div>
      <div class="nickname">
        <input class="signup_required" type="text" name="nickname" placeholder="닉네임(8자 이하)"
               required pattern="^[a-zA-Z0-9가-힣]{1,8}$" oninvalid="this.setCustomValidity('8자 이하만 가능합니다.')"
               oninput="this.setCustomValidity('')"  autocomplete="off"/>
      </div>
      <button class="signup_required signup_btn">회원가입</button>
    </form>
  </div>


  <!--jquery-->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script>
{% if alert_message %}
    alert(alert_message);
{% endif %}
</script>

>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
{% endblock %}

info/accounts/templates/accounts/user_activate_email.html
<<<<<<< HEAD
{% autoescape off %}
안녕하세요, {{ user.last_name }}님!
서울시립대학교 음식점 정보 제공 서비스, BLD에 가입해주셔서 정말 감사합니다! ^^

아래 링크를 클릭하면 회원가입 인증이 완료됩니다.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}


P.S. {{ user.last_name }}님께서 대학 생활 중 필요하신 웹 서비스나
불편하다고 느끼신 웹 서비스 있으시면, 새롭게 만들어 보려고 합니다(아래 설문 조사에 참여해주세요!)
=======
{% autoescape off %}
안녕하세요, {{ user.last_name }}님!
서울시립대학교 음식점 정보 제공 서비스, BLD에 가입해주셔서 정말 감사합니다! ^^

아래 링크를 클릭하면 회원가입 인증이 완료됩니다.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}


P.S. {{ user.last_name }}님께서 대학 생활 중 필요하신 웹 서비스나
불편하다고 느끼신 웹 서비스 있으시면, 새롭게 만들어 보려고 합니다(아래 설문 조사에 참여해주세요!)
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
{% endautoescape %}