info/asitis/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "asitis"

urlpatterns = [
    path('', views.base, name="base"),
    path('detail/<int:pk>', views.detail, name="detail"),
    # path('like', views.comment_like, name='comment_like'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/config/urls.py
<<<<<<< HEAD
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('asitis/', include('asitis.urls')),
    path('notice_spider/', include('notice_spider.urls')),
]

=======
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('asitis/', include('asitis.urls')),
    path('notice_spider/', include('notice_spider.urls')),
]

>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/asitis/models.py
<<<<<<< HEAD
from django.db import models
from django.conf import settings


# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=16, verbose_name='과목명',)
    professor = models.CharField(max_length=16, verbose_name='교수명', null=True, blank=True)
    code = models.CharField(max_length=8, verbose_name='과목코드',)
    department = models.CharField(max_length=16, verbose_name='소속 대학명',)
    major = models.CharField(max_length=16, verbose_name='전공',)
    course = models.CharField(max_length=8, verbose_name='교양/전공 여부',)
    grade = models.CharField(max_length=8, verbose_name='수강 학년',)
    semester = models.TextField(verbose_name='학기',)


class Jokbo(models.Model):
    STATUS_CHOICES1 = (
        ('파일 검토 중', '파일 검토 중'),
        ('허가', '허가'),
    )
    admit = models.TextField(choices=STATUS_CHOICES1, verbose_name='허가 여부', null=True, blank=True,)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자', null=True,)
    file = models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='족보 파일',)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name='해당 수업')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
=======
from django.db import models
from django.conf import settings


# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=16, verbose_name='과목명',)
    professor = models.CharField(max_length=16, verbose_name='교수명', null=True, blank=True)
    code = models.CharField(max_length=8, verbose_name='과목코드',)
    department = models.CharField(max_length=16, verbose_name='소속 대학명',)
    major = models.CharField(max_length=16, verbose_name='전공',)
    course = models.CharField(max_length=8, verbose_name='교양/전공 여부',)
    grade = models.CharField(max_length=8, verbose_name='수강 학년',)
    semester = models.TextField(verbose_name='학기',)


class Jokbo(models.Model):
    STATUS_CHOICES1 = (
        ('파일 검토 중', '파일 검토 중'),
        ('허가', '허가'),
    )
    admit = models.TextField(choices=STATUS_CHOICES1, verbose_name='허가 여부', null=True, blank=True,)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자', null=True,)
    file = models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='족보 파일',)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name='해당 수업')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa

info/asitis/views.py
from django.shortcuts import render
from .models import Subject
from django.db.models import Q
# from .importing_class_list import importing_class_list


# Create your views here.
# 이미 importing 작업 끝냄
# importing_class_list()

def base(request):
    # 족보 search 기능 구현(등록과 검색 따로 받음)
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            subjects = Subject.objects.filter(
                Q(name__icontains=search_term) |
                Q(professor__icontains=search_term)
            ).distinct().order_by('name')
            for subject in subjects:
                subject.name = list(subject.name.partition(search_term))
                subject.professor = list(subject.professor.partition(search_term))
            # select 무엇이 되었는지 구별(족보 등록인지 족보 검색인지)
            if "select" in request.GET:
                select = request.GET["select"]
        ctx = {
            'select': select,
            'search_term': search_term,
            'subjects': subjects
        }
        return render(request, 'asitis/search.html', ctx)
    ctx = {}
    return render(request, 'asitis/base.html', ctx)


def detail(request, pk):
    # 족보 search 기능 구현(등록과 검색 따로 받음)
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            subjects = Subject.objects.filter(
                Q(name__icontains=search_term) |
                Q(professor__icontains=search_term)
            ).distinct().order_by('name')
            for subject in subjects:
                subject.name = list(subject.name.partition(search_term))
                subject.professor = list(subject.professor.partition(search_term))
            # select 무엇이 되었는지 구별(족보 등록인지 족보 검색인지)
            if "select" in request.GET:
                select = request.GET["select"]
        ctx = {
            'select': select,
            'search_term': search_term,
            'subjects': subjects
        }
        return render(request, 'asitis/search.html', ctx)
    subject = Subject.objects.filter(pk=pk)
    ctx = {
        'subject': subject
    }
    return render(request, 'asitis/detail.html', ctx)

info/asitis/templates/asitis/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>그대로 나왔네</title>
  <link rel="stylesheet" type="text/css" href="{% static 'asitis/css/base.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
</head>
<body>
<!--header-->
<div id="header">
  <div id="menu">
    <img src="{% static 'asitis/images/menu2.png' %}" width="25">
  </div>
  <a href="{% url "asitis:base" %}" id="title"><p>그대로<br/>나왔네</p></a>
  <div id="book_mark">
    <img src="{% static 'asitis/images/star1.png' %}" width="25">
  </div>
</div>

<!--select_bar-->
<div id="select_box">
  <div id="select_register" class="select_bar">족보를 등록합니다</div>
  <div id="select_search" class="select_bar">족보를 검색합니다</div>
</div>

{% block main %}
<!--search_box-->
<div style="display: none" id="search_box">
  <div id="search_bar">
    <form method="get" action="" id="search_form">
      <input id="search" type="text" name="search" placeholder="강의명, 교수명" required>
      <input id="select" type="hidden" name="select">
    </form>
    <div style="display: none" id="search_btn">
      <img src="{% static 'asitis/images/search.png' %}" height="18">
    </div>
  </div>
</div>
{% endblock %}

<!--footer-->
<div id="footer">

</div>



</body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'asitis/js/base.js' %}"></script>
  {% block script %}
  {% endblock %}
</html>

info/asitis/templates/asitis/detail.html
{% extends "asitis/base.html" %}

{% block main %}
{% load static %}
<!--search_box-->
<link rel="stylesheet" type="text/css" href="{% static 'asitis/css/search.css' %}">
<div id="search_box">
  <div id="search_bar">
    <form method="get" action="" id="search_form">
      <input id="search" type="text" name="search" placeholder="강의명, 교수명" value="{{ search_term }}" required>
      <input id="select" type="hidden" name="select">
    </form>
    <div style="display: none" id="search_btn">
      <img src="{% static 'asitis/images/search.png' %}" height="18">
    </div>
  </div>
</div>

<!--detail-->
<div>
  
</div>

{% endblock %}


{% block script %}
<script type="text/javascript" src="{% static 'asitis/js/search.js' %}"></script>
<script>
var select = "{{ select }}";

if (select === "register") {
    $('#select_register').addClass('black');
} else {
    $('#select_search').addClass('black');
};
</script>
{% endblock %}

info/asitis/templates/asitis/search.html
<<<<<<< HEAD
{% extends "asitis/base.html" %}

{% block main %}
{% load static %}
<!--search_box-->
<link rel="stylesheet" type="text/css" href="{% static 'asitis/css/search.css' %}">
<div id="search_box">
  <div id="search_bar">
    <form method="get" action="" id="search_form">
      <input id="search" type="text" name="search" placeholder="강의명, 교수명" value="{{ search_term }}" required>
      <input id="select" type="hidden" name="select">
    </form>
    <div style="display: none" id="search_btn">
      <img src="{% static 'asitis/images/search.png' %}" height="18">
    </div>
  </div>
</div>

<!--class_list-->
<div id="class_list">
  {% for subject in subjects %}
    <a href="#" id="class_box">
      <div id="class_box_left" class="class_box_contents">
        <div id="class_box_name">
          {% for subject_name_split in subject.name %}
            {% if subject_name_split == search_term %}
              <span style="background-color: #DCDCDC;">{{ subject_name_split }}</span>
            {% else %}
              <span>{{ subject_name_split }}</span>
            {% endif %}
          {% endfor %}
        </div>
        <div id="class_box_professor">
          {% for subject_professor_split in subject.professor %}
            {% if subject_professor_split == search_term %}
              <span style="background-color: #DCDCDC;">{{ subject_professor_split }}</span>
            {% else %}
              <span>{{ subject_professor_split }}</span>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <div id="class_box_right" class="class_box_contents">
        <img src="{% static 'asitis/images/star4.png' %}" width="22">
      </div>
    </a>
  {% endfor %}
</div>
{% endblock %}


{% block script %}
<script type="text/javascript" src="{% static 'asitis/js/search.js' %}"></script>
<script>
var select = "{{ select }}";

if (select === "register") {
    $('#select_register').addClass('black');
} else {
    $('#select_search').addClass('black');
};
</script>
=======
{% extends "asitis/base.html" %}

{% block main %}
{% load static %}
<!--search_box-->
<link rel="stylesheet" type="text/css" href="{% static 'asitis/css/search.css' %}">
<div id="search_box">
  <div id="search_bar">
    <form method="get" action="" id="search_form">
      <input id="search" type="text" name="search" placeholder="강의명, 교수명" value="{{ search_term }}" required>
      <input id="select" type="hidden" name="select">
    </form>
    <div style="display: none" id="search_btn">
      <img src="{% static 'asitis/images/search.png' %}" height="18">
    </div>
  </div>
</div>

<!--class_list-->
<div id="class_list">
  {% for subject in subjects %}
    <a href="#" id="class_box">
      <div id="class_box_left" class="class_box_contents">
        <div id="class_box_name">
          {% for subject_name_split in subject.name %}
            {% if subject_name_split == search_term %}
              <span style="background-color: #DCDCDC;">{{ subject_name_split }}</span>
            {% else %}
              <span>{{ subject_name_split }}</span>
            {% endif %}
          {% endfor %}
        </div>
        <div id="class_box_professor">
          {% for subject_professor_split in subject.professor %}
            {% if subject_professor_split == search_term %}
              <span style="background-color: #DCDCDC;">{{ subject_professor_split }}</span>
            {% else %}
              <span>{{ subject_professor_split }}</span>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <div id="class_box_right" class="class_box_contents">
        <img src="{% static 'asitis/images/star4.png' %}" width="22">
      </div>
    </a>
  {% endfor %}
</div>
{% endblock %}


{% block script %}
<script type="text/javascript" src="{% static 'asitis/js/search.js' %}"></script>
<script>
var select = "{{ select }}";

if (select === "register") {
    $('#select_register').addClass('black');
} else {
    $('#select_search').addClass('black');
};
</script>
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
{% endblock %}